### ISSUE TITLE
How to filter url in capturing list with fiddler-everywhere?

### ISSUE THREAD

**Issue by gitfourteen** [telerik/fiddler-everywhere-docs#10]
macOS Catalina
Succeed capturing, but I would like to show only specific sites.

**Comment by bsivanov** [comment]
This repo is related only to the Fiddler Everywhere documentation. For questions you can use the [Fiddler Everywhere forums](https://www.telerik.com/forums/fiddler#ctl00_GeneralContent_C007_forumsFrontendList_ctl00_ctl00_list_ctrl9_isGroupConditional_ctl00_statusImageGroup), and for requests the [Fiddler Everywhere feedback portal](https://feedback.telerik.com/fiddler-everywhere). Still, the team is currently working on the [filtering feature](https://feedback.telerik.com/fiddler-everywhere/1386703-add-filtering-options-for-capturing-traffic-for-mac-os), so follow the item to stay tuned.

**Comment by Banyc** [comment]
After almost a year since this issue, however, the filter only works on headers, having nothing to do with URL.

**Comment by mcm-ham** [comment]
You can try filtering by Origin header.

**Comment by darcho** [comment]
Click on the 3 vertical dots in the header of the table to filter by the column
