### ISSUE TITLE
How to reinstall Fiddler Everywhere on Ubuntu

### ISSUE THREAD

**Issue by khtan** [telerik/fiddler-everywhere-docs#11]
When I first tried Fiddler Everywhere on my Ubuntu machine, I downloaded it to ~/Download
and ran it from there, accidentally agreeing to update the Applications folder etc.
This was to confirm that Fiddler Everywhere would run on Ubuntu.

Now knowing better, I wanted to move the AppImage to ~/programs and re-generate the Application links etc.
I can still run the AppImage directly but the Applications folder is no longer correct.

How do I reinstall Fiddler Everywhere and still trigger the updates to Application links?

**Comment by danger89** [comment]
Maybe just change the command of the launcher (in your menu): 
![image](https://user-images.githubusercontent.com/628926/79802838-0fe5b480-8361-11ea-9d09-4484b034017d.png)

(XFCE is my window manager)

**Comment by bsivanov** [comment]
Hello all, this repo is used only for the documentation of Fiddler Everywhere, could you move future discussion to the [Fiddler Everywhere on Linux](https://www.telerik.com/forums/fiddler/linux) forum? Also stay tuned, we are preparing an official release which is due in some weeks. To get the early bits, you can also join the [Fiddler Insiders program](https://www.telerik.com/fiddler-everywhere#GeneralContent_C384_Col00).

**Comment by danger89** [comment]
@bsivanov  Thanks, sorry for the offtopic. But I really like fully-featured Fiddle EveryWhere under Linux, that would be awesome! Like changing the requests (which is now not possible).

I joined the insiders program right away.
