### ISSUE TITLE
Can't select my VPN connection

### ISSUE THREAD

**Issue by spitoman** [telerik/fiddler-everywhere-docs#12]
In the normal Fiddler program, I can select my VPN connection that I setup in Windows 10, but in the new Fiddler, there is no option in the settings to do that. and because of this, no connection is shown.

**Comment by NickIliev** [comment]
Please post your issue [in the public Fiddler forums](https://www.telerik.com/forums/fiddler). This repository is fir loving issue and creating discussion related to the upcoming Fiddler documentation.

**Comment by NickIliev** [comment]
FYI: A solution for using VPN tools (like CiscoVPN) is posted in [this KB article](https://docs.telerik.com/fiddler-everywhere/knowledge-base/configure-vpn-with-fiddler).
