### ISSUE TITLE
Why does the website show a table of contents of only <h2>?

### ISSUE THREAD

**Issue by lwcorp** [telerik/fiddler-everywhere-docs#277]
The documents use `<h3>`, `<h4>`, etc.  but the actual website just seems to ignore them, and only treats `<h2>` in the automated table of contents.

For example:
https://docs.telerik.com/fiddler-everywhere/knowledge-base/how-to-mock-responses
![image](https://user-images.githubusercontent.com/1773306/183592410-9ca72590-95f6-473a-8e26-a829ac4d3545.png)
VS
https://github.com/telerik/fiddler-everywhere-docs/blob/master/knowledge-base/how-to-mock-responses.md
![image](https://user-images.githubusercontent.com/1773306/183592921-eaa49bab-f17c-481b-ac78-8896c7791d72.png)

Can you please make all table of contents present all `<hX>`s? It will help navigation so much more helpful, easier and quicker.

**Comment by NickIliev** [comment]
The documentation is hosted under the Telerik.com family and uses a common style and UI that is outside our control. Currently, only h1 and h2 titles are indexed and shown in the side menu. Lower titles (H3 and H4) are still generating quick links that can be reused (e.g. in external links or for creating our own custom embedded table of content) but won't be shown in the automated side table of content.
