### ISSUE TITLE
Unable to get macOS Mojave capture

### ISSUE THREAD

**Issue by jeolsen** [telerik/fiddler-everywhere-docs#6]
When i start Fiddler on macOS Mojave 10.14.3 i do not see any results.  "Capturing..." is displayed and i've enabled HTTPS decryption and imported the certificate (and trusted it) in Keychain Access.  I've tried browsing on Chrome, Firefox, and Safari, but do not see anything get captured.  It's just showing "No records available".  Am i missing a step?  I do have a system proxy configured that uses a PAC file if that matters.

Thanks

**Comment by msorens** [comment]
Same problem for me, except I am running macOS Mojave 10.14.5 and I see "Capture" displayed and I have also trusted the certificate as instructed in your docs. The main pane simply says "No sessions to display".

**Comment by L5eoneill** [comment]
On my macOS, Mojave 10.14.5, and Fiddler Everywhere v 0.4.0, "Capture" is a button that does not change anything when clicked. The Capture button is missing from the documentation (which is what this repo is all about: documentation).

**Comment by tpaulengineer** [comment]
I can capture but where is autoresponder?
I tried the Mono version and got it working, except when I try to add TLS 1.2 in the interface, it blows up... ideas?

**Comment by youchen** [comment]
Catalina v10.15.4, Fiddler v0.5.0

On Firefox v75
1. Manual Proxy
2. HTTP Proxy (check "also use this proxy for FTP and HTTPS"): 127.0.0.1
3. Port: 8866 (which you can set on Fiddler - Settings - Connections)

It's working for me.

**Comment by jeolsen** [comment]
@youchen, that works in FF for me as well.  But in Fiddler - Settings - Connections on that same screen i have "Act as system proxy on startup". Edge Chromium, Chrome, and Safari are all forced by policy to use the System Proxy and that doesn't seem to be working.  So shouldn't Fiddler adjust the system proxy so it sits in the middle when it starts up?

**Comment by NickIliev** [comment]
Hey everyone, 

The latest version of Fiddler Everywhere includes multiple improvements and fixes related to setting up the Fiddler proxy on macOS.  Please let us know if you are still experiencing trouble and provide as much information as possible about your current setup.

Additionally, note that you could receive help from [our Fiddler Everywhere forums](https://community.getfiddler.com/support/discussions/12000000385) where similar threads are discussed and investigated by the team and community members
