### ISSUE TITLE
Crash on mac os 10.11

### ISSUE THREAD

**Issue by minopica** [telerik/fiddler-everywhere-docs#7]
I am unable to launch Fiddler everywhere on mac os v10.11: it crashes systematically.

**Comment by Aliasr** [comment]
Same here. Fiddler crashes while loading. Did you find any solution?

**Comment by Aliasr** [comment]
Digging a little more I found this:

> read(0x38, "dyld: lazy symbol binding failed: Symbol not found: _clock_gettime\n  Referenced from: /Applications/Progress Telerik Fiddler.app/Contents/Resources/app/out/WebServer/libcoreclr.dylib (which was built for Mac OS X 10.12)\n  Expected in: /usr/lib/libSystem.B.", 0x10000)

Here's a Stackoverflow thread about it:

https://stackoverflow.com/questions/45833569/dyld-lazy-symbol-binding-failed-symbol-not-found-clock-gettime-in-mongodb

I hope they add support for Mac Os X below 10.12.

**Comment by bugatsinho** [comment]
running mono --arch=32 Fiddler.exe
gives me this error

> “mono-sgen32” is not optimized for your Mac and needs to be updated

> 
and also contact with developer

**Comment by bsivanov** [comment]
Hello all, this repo is used only for the documentation of Fiddler Everywhere, could you move future discussion to the [Fiddler Everywhere on Mac](https://www.telerik.com/forums/fiddler/mac) forum? Also stay tuned, we are preparing an official release which is due in some weeks. To get the early bits, you can also join the [Fiddler Insiders program](https://www.telerik.com/fiddler-everywhere#GeneralContent_C384_Col00).
