### ISSUE TITLE
Assumes path to Desktop is static

### ISSUE THREAD

**Issue by tinywiz** [telerik/fiddler-everywhere-docs#9]
Hi.

When exporting ssl certificate fiddler assumes that the path is something like:
"C:\Users\'username'\desktop"

The following error shows:
"Could not find part of the path"

However I use a different location for my desktop and no option is available to choose a specific destination to save the certificate.

**Comment by bsivanov** [comment]
This repo is about [Fiddler Everywhere documentation](https://docs.telerik.com/fiddler-everywhere/introduction). For bugs and reports, you can use the [Fiddler Everywhere feedback portal](https://feedback.telerik.com/fiddler-everywhere/). Thanks for the report anyway, I went ahead and logged the bug in the portal: [Root certificate cannot be exported when Windows Desktop is with changed location](https://feedback.telerik.com/fiddler-everywhere/1439961-root-certificate-cannot-be-exported-when-windows-desktop-is-with-changed-location).
